language: node_js
node_js:
- 4
notifications:
  email: false
deploy:
  provider: npm
  email: k88hudson@gmail.com
  on:
    branch: master
    tags: true
  api_key:
    secure: EuksC2XzZIuvZiYP/6cgfXREYEr2Z1Qdf3hEX+6Z35H9tCOAGzpy8Wc3iXFodfSbi/NghSmnrfFc84wheJqyE27ms1msXeHn322Bnm3weiZc2+l6lthxrZ2HaJ686nGkjNSsm8AWvhcRKh4avmYdqLmrXn9g3Sy/ENKhvzvOThuctGQrhXm9lviey48Z4ZOSBJUtxvw+z3WV+rgYYf+LEJBpYWQO4c9YhdQoyXaSpCNp1CT2FzEP/FSzGRvaDmB0/nDGAb3hoNCugZTua9UFJiE5sI5pphYtBd/9JbB8yhq5vB7odZgjzPLiQDFp8dTDZDqOPY5/XrOmISwzJTrY/aF9itZreeUBTIybjJBKIGg80teioONj5W6cMTxv11LUHGNEnzsEnjclkrV4NGn5e6xAY4NvclNq+YZEOVez1+iSxxfmPZxkZoRbepcxq9ncaKOZE0t3omOpynPerZwEsGAcXcHe4tOhj9hXP7sxLbA9CtFzkujRiZhvN5q3U922XTj5gXET54sbCPRIYjULJ4LCR2remY2GRZcorNTyN/+pqGiJFwuOE9Aq1fgiokgRDSdgXZh96ePgvqTAq4GIGknrqCZIFZAzzvJZcmcScba8S7Dsz0OUj9Hviy0cK1bAzGac9NXG6cfZ4R3GNeVDdeNE+XK2xeJKaznUm7udxvQ=
